---
# Note: this playbook relies on `xps` variable. The `xps` variable is
# a list that contains the name of all experimentation. For instance,
# this list is as following for the idle experimentation.
# - idle-cpt20-nfk05
# - idle-cpt20-nfk10
# - idle-cpt20-nfk25
# - idle-cpt20-nfk50
- hosts: all
  tasks:
  - name: The list of experimentation
    debug: var=xps

  - name: Making the results and archives directories
    file: path=/results/archives state=directory

  - name: Getting results from home and put them into /results/archives
    command: "cp /home/{{ item }}.tar.gz /results/archives/"
    args:
      creates: "/results/archives/{{ item }}.tar.gz"
    with_items: "{{ xps }}"

  - name: Extracting experimentation results
    command: "tar -C /results -xzf /results/archives/{{ item }}.tar.gz"
    args:
      creates: "/results/{{ item }}"
    with_items: "{{ xps }}"

  # TODO: Ensures that there are rally report to extract
  # - name: Extracting rally report
  #   shell: "tar -C /results/{{ item }} -xzf /results/{{ item }}/*rally.tar.gz"
  #   args:
  #     creates: "/results/{{ item }}/report"
  #   with_items: "{{ xps }}"

  - name: Extracting influx database
    shell: "tar -C /results/{{ item }} -xzf /results/{{ item }}/*-influxdb.tar.gz"
    args:
      creates: "/results/{{ item }}/influx-data"
    with_items: "{{ xps }}"

  # XXX: Bind each start to a specific port
  - name: Starting influx container
    docker:
      detach: yes
      image: "tutum/influxdb:0.13"
      net: host
      state: started
      volumes: "/results/{{ item }}/influx-data:/data"
    with_items: "{{ xps }}"

  - name: Starting grafana container
    docker:
      detach: yes
      image: "grafana/grafana:3.1.0"
      name: "grafana"
      ports: "3000:3000"
      state: started

  - name: Coping the nginx configuration file
    copy: src="files/nginx.conf" dest="/nginx.conf"

  - name: Starting the nginx server container
    docker:
      detach: yes
      image: "nginx:alpine"
      name: "influx"
      ports: "80:80"
      volumes:
        - "/results:/usr/share/nginx/html"
        - "/nginx.conf:/etc/nginx/nginx.conf"
